version: '3'

volumes:
  db-data:

networks:
  status_checker_net:

services:
  site:
    volumes:
      - .:/var/www/html
      - ./config/vhost.conf:/etc/apache2/sites-available/000-default.conf
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/site/public
    ports:
      - 80:80
    build:
      context: .
    networks:
      - status_checker_net

  db:
    image:  mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=status_checker
    networks:
      - status_checker_net